docs(quickstart): proofreading and cosmetic edits
werf/trdl pull request #158
Opened 2021-12-09 14:57 UTC by olegznv

2021-12-09 16:57 UTC, alexey-igrychev requested changes

2021-12-10 08:41 UTC, olegznv reviewed
@alexey-igrychev пофиксил все замечания

2021-12-10 08:41 UTC, olegznv commented on docs/pages_ru/QUICKSTART.md
> +* номер доверенной версии (`ROOT_VERSION`) и хеш-сумма соответствующего файла `<VERSION>.root.json` (`ROOT_SHA512`), которые вендор должен предоставить пользователю для верификации TUF-репозитория пр
Поправил

2021-12-10 13:20 UTC, alexey-igrychev requested changes

2021-12-10 13:20 UTC, alexey-igrychev commented on docs/pages_ru/QUICKSTART.md
> +При добавлении репозитория пользователю потребуются данные, которые вендор должен предоставить пользователю для верификации TUF-репозитория при первичном обращении: произвольное имя (`REPO`), адрес T
```suggestion
При добавлении репозитория пользователю потребуются данные, которые вендор должен предоставить пользователю для верификации TUF-репозитория при первичном обращении: адрес TUF-репозитория (`URL`), номер доверенной версии (`ROOT_VERSION`) и хеш-сумма соответствующего файла `<VERSION>.root.json` (`ROOT_SHA512`).
```

2021-12-10 13:20 UTC, alexey-igrychev commented on docs/pages_ru/QUICKSTART.md
> +Данные, которые пользователь получает у вендора:
```suggestion
В нашем случае пользователь получает следующие данные от вендора:
```

2021-12-10 13:31 UTC, alexey-igrychev approved these changes

2021-12-10 13:32 UTC, merged